# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-12 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('color', models.CharField(max_length=255, verbose_name='Color')),
                ('produced_at', models.DateTimeField(auto_now_add=True)),
                ('is_eaten', models.BooleanField(default=False)),
            ],
        ),
    ]
